language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

  # command to install dependencies
install:
  #- pip install pandas
  - python setup.py install
  #- pip install matplotlib
  #- travis_wait pip install scipy
# command to run tests
script: python spotpy/examples/tutorial_rosenbrock.py
script: python spotpy/unittests/test_database.py
script: python spotpy/unittests/test_signatures.py
